<a href="https://colab.research.google.com/github/vtu28901-gif/10215CS180---SS-26-27---Synthetic-Data-generation-using-Generative-AI/blob/main/Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Part A — LOAD THE DATA**

In [ ]:
import pandas as pd

# Load the dataset
df = pd.read_csv('/content/glixify_dataset1.csv')
display(df.head())

,participant_id,timestamp,glucose_mg_dl,heart_rate_bpm,hrv_ms,spo2_percent,sleep_duration_hours,activity_level,steps,sleep_quality,device_type
0,P063,08-01-2026 04:00,107.840082,65.454512,54.239094,96.017807,5.500982,Low,252.0,Fair,Wearable_A
1,P047,08-01-2026 12:00,105.758855,63.699755,48.234028,95.728198,NaN,Low,37.0,NaN,Wearable_A
2,P018,22-01-2026 07:00,97.844208,74.428713,51.861775,97.958764,NaN,Moderate,1209.0,NaN,Wearable_C
3,P048,09-01-2026 18:00,112.451573,66.269009,39.164509,97.602378,NaN,Low,527.0,NaN,Wearable_A
4,P046,14-01-2026 21:00,121.005022,66.406237,48.133023,98.483996,NaN,Moderate,1246.0,NaN,Wearable_B

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/glixify_dataset.csv")

In [ ]:
df.head()  #This is important because later you generate approximately the same number of synthetic rows.

,participant_id,timestamp,glucose_mg_dl,heart_rate_bpm,hrv_ms,spo2_percent,sleep_duration_hours,activity_level,steps,sleep_quality,device_type
0,P063,08-01-2026 04:00,107.840082,65.454512,54.239094,96.017807,5.500982,Low,252.0,Fair,Wearable_A
1,P047,08-01-2026 12:00,105.758855,63.699755,48.234028,95.728198,NaN,Low,37.0,NaN,Wearable_A
2,P018,22-01-2026 07:00,97.844208,74.428713,51.861775,97.958764,NaN,Moderate,1209.0,NaN,Wearable_C
3,P048,09-01-2026 18:00,112.451573,66.269009,39.164509,97.602378,NaN,Low,527.0,NaN,Wearable_A
4,P046,14-01-2026 21:00,121.005022,66.406237,48.133023,98.483996,NaN,Moderate,1246.0,NaN,Wearable_B

In [ ]:
df.shape

(10000, 11)

In [ ]:
df.columns #learning the schema of the dataset

Index(['participant_id', 'timestamp', 'glucose_mg_dl', 'heart_rate_bpm',
       'hrv_ms', 'spo2_percent', 'sleep_duration_hours', 'activity_level',
       'steps', 'sleep_quality', 'device_type'],
      dtype='object')

In [ ]:
df.head()

,participant_id,timestamp,glucose_mg_dl,heart_rate_bpm,hrv_ms,spo2_percent,sleep_duration_hours,activity_level,steps,sleep_quality,device_type
0,P063,08-01-2026 04:00,107.840082,65.454512,54.239094,96.017807,5.500982,Low,252.0,Fair,Wearable_A
1,P047,08-01-2026 12:00,105.758855,63.699755,48.234028,95.728198,NaN,Low,37.0,NaN,Wearable_A
2,P018,22-01-2026 07:00,97.844208,74.428713,51.861775,97.958764,NaN,Moderate,1209.0,NaN,Wearable_C
3,P048,09-01-2026 18:00,112.451573,66.269009,39.164509,97.602378,NaN,Low,527.0,NaN,Wearable_A
4,P046,14-01-2026 21:00,121.005022,66.406237,48.133023,98.483996,NaN,Moderate,1246.0,NaN,Wearable_B

In [ ]:
df["timestamp"].head(20)

0     08-01-2026 04:00
1     08-01-2026 12:00
2     22-01-2026 07:00
3     09-01-2026 18:00
4     14-01-2026 21:00
5     25-01-2026 16:00
6     09-01-2026 04:00
7     18-01-2026 02:00
8     26-01-2026 15:00
9     21-01-2026 15:00
10    09-01-2026 02:00
11    14-01-2026 15:00
12    21-01-2026 00:00
13    13-01-2026 05:00
14    20-01-2026 03:00
15    06-01-2026 09:00
16    09-01-2026 10:00
17    08-01-2026 06:00
18    25-01-2026 03:00
19    22-01-2026 10:00
Name: timestamp, dtype: object

In [ ]:
df["timestamp"].dtype

dtype('O')

In [ ]:
df["timestamp"].unique()[:20]

array(['08-01-2026 04:00', '08-01-2026 12:00', '22-01-2026 07:00',
       '09-01-2026 18:00', '14-01-2026 21:00', '25-01-2026 16:00',
       '09-01-2026 04:00', '18-01-2026 02:00', '26-01-2026 15:00',
       '21-01-2026 15:00', '09-01-2026 02:00', '14-01-2026 15:00',
       '21-01-2026 00:00', '13-01-2026 05:00', '20-01-2026 03:00',
       '06-01-2026 09:00', '09-01-2026 10:00', '08-01-2026 06:00',
       '25-01-2026 03:00', '22-01-2026 10:00'], dtype=object)

# ***Part B — UNDERSTAND DATA TYPES ***

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   participant_id        10000 non-null  object
 1   timestamp             10000 non-null  object
 2   glucose_mg_dl         9719 non-null   float64
 3   heart_rate_bpm        10000 non-null  float64
 4   hrv_ms                9797 non-null   float64
 5   spo2_percent          9869 non-null   float64
 6   sleep_duration_hours  3200 non-null   float64
 7   activity_level        10000 non-null  object
 8   steps                 9665 non-null   float64
 9   sleep_quality         3200 non-null   object
 10  device_type           10000 non-null  object
dtypes: float64(6), object(5)
memory usage: 859.5+ KB

# **Part C — Check Missing Values**

In [ ]:
df.isnull().sum()

participant_id             0
timestamp                  0
glucose_mg_dl            281
heart_rate_bpm             0
hrv_ms                   203
spo2_percent             131
sleep_duration_hours    6800
activity_level             0
steps                    335
sleep_quality           6800
device_type                0
dtype: int64

In [ ]:
df.isnull().mean() * 100

participant_id           0.00
timestamp                0.00
glucose_mg_dl            2.81
heart_rate_bpm           0.00
hrv_ms                   2.03
spo2_percent             1.31
sleep_duration_hours    68.00
activity_level           0.00
steps                    3.35
sleep_quality           68.00
device_type              0.00
dtype: float64

In [ ]:
missing = df.isnull().sum()

missing[missing > 0]

glucose_mg_dl            281
hrv_ms                   203
spo2_percent             131
sleep_duration_hours    6800
steps                    335
sleep_quality           6800
dtype: int64

In [ ]:
df[["sleep_duration_hours", "sleep_quality"]].isnull().sum()  #Check whether missing sleep values occur together

sleep_duration_hours    6800
sleep_quality           6800
dtype: int64

In [ ]:
df[["sleep_duration_hours", "sleep_quality"]].isnull().all(axis=1).sum() #How many rows have both sleep duration AND sleep quality missing?

np.int64(6800)

In [ ]:
df[["sleep_duration_hours", "sleep_quality"]].notnull().all(axis=1).sum() #How many rows have both sleep measurements present?

np.int64(3200)

In [ ]:
df.groupby("activity_level")[
    ["sleep_duration_hours", "sleep_quality"]
].apply(lambda x: x.notnull().mean() * 100) #Check whether sleep availability relates to activity          #This is profiling

                sleep_duration_hours  sleep_quality
activity_level
High                        7.377980       7.377980
Low                        48.900052      48.900052
Moderate                    9.324567       9.324567

# **Part D — Numerical** **Profile**

In [ ]:
df.describe()

,glucose_mg_dl,heart_rate_bpm,hrv_ms,spo2_percent,sleep_duration_hours,steps
count,9719.000000,10000.000000,9797.000000,9869.000000,3200.000000,9665.000000
mean,106.251486,72.727045,46.052792,97.020902,6.813300,894.711433
std,13.794711,6.743651,8.858883,0.899899,0.698415,974.639706
min,65.000000,52.129685,15.669435,94.296831,4.313245,0.000000
25%,96.804580,67.850885,39.696226,96.369614,6.362490,223.000000
50%,105.772871,72.325500,45.958480,96.967141,6.810498,404.000000
75%,115.056572,77.341893,52.310568,97.623990,7.269670,1417.000000
max,159.905687,97.000467,73.870399,100.404306,9.255195,5773.000000

In [ ]:
df["activity_level"].value_counts()

activity_level
Low         5773
Moderate    3346
High         881
Name: count, dtype: int64

In [ ]:
df["activity_level"].value_counts(normalize=True) * 100

activity_level
Low         57.73
Moderate    33.46
High         8.81
Name: proportion, dtype: float64

In [ ]:
df["sleep_quality"].value_counts()

sleep_quality
Good    1810
Fair    1027
Poor     363
Name: count, dtype: int64

In [ ]:
df["device_type"].value_counts()

device_type
Wearable_A    4529
Wearable_B    3458
Wearable_C    2013
Name: count, dtype: int64

# **PART E-Exploring Relationships Between Variables**

In [ ]:
numeric_cols = [
    "glucose_mg_dl",
    "heart_rate_bpm",
    "hrv_ms",
    "spo2_percent",
    "sleep_duration_hours",
    "steps"
]

corr = df[numeric_cols].corr()

corr.round(2)

,glucose_mg_dl,heart_rate_bpm,hrv_ms,spo2_percent,sleep_duration_hours,steps
glucose_mg_dl,1.00,-0.06,0.16,0.00,-0.01,-0.05
heart_rate_bpm,-0.06,1.00,-0.15,-0.16,-0.02,0.44
hrv_ms,0.16,-0.15,1.00,0.15,0.00,-0.21
spo2_percent,0.00,-0.16,0.15,1.00,0.01,-0.09
sleep_duration_hours,-0.01,-0.02,0.00,0.01,1.00,0.00
steps,-0.05,0.44,-0.21,-0.09,0.00,1.00

In [ ]:
df.groupby("activity_level")["heart_rate_bpm"].agg(
    ["count", "mean", "median", "std"]
).round(2)

                count   mean  median   std
activity_level
High              881  80.03   79.81  5.77
Low              5773  70.17   69.83  5.92
Moderate         3346  75.22   74.85  5.93

In [ ]:
df.groupby("activity_level")["steps"].agg(
    ["count", "mean", "median"]
).round(2)

                count     mean  median
activity_level
High              851  3174.65  3174.0
Low              5594   254.27   252.0
Moderate         3220  1404.78  1405.0

# **Part F — What should our synthetic data preserve?**

In [ ]:
baseline = df.sample(
    n=len(df),
    replace=True,                         #bootstrap resampling
    random_state=42
).reset_index(drop=True)

In [ ]:
baseline.shape

(10000, 11)

In [ ]:
numeric_cols = [
    "glucose_mg_dl",        #comparing numerical
    "heart_rate_bpm",
    "hrv_ms",
    "spo2_percent",
    "sleep_duration_hours",
    "steps"
]

comparison = pd.DataFrame({
    "real_mean": df[numeric_cols].mean(),
    "baseline_mean": baseline[numeric_cols].mean(),
    "real_std": df[numeric_cols].std(),
    "baseline_std": baseline[numeric_cols].std()
}).round(2)

comparison

                      real_mean  baseline_mean  real_std  baseline_std
glucose_mg_dl            106.25         106.29     13.79         13.79
heart_rate_bpm            72.73          72.63      6.74          6.79
hrv_ms                    46.05          46.11      8.86          8.83
spo2_percent              97.02          97.03      0.90          0.90
sleep_duration_hours       6.81           6.83      0.70          0.70
steps                    894.71         898.04    974.64        963.46

In [ ]:
activity_compare = pd.DataFrame({
    "real_%": df["activity_level"].value_counts(normalize=True) * 100, #Compare categorical
    "baseline_%": baseline["activity_level"].value_counts(normalize=True) * 100
}).round(2)

activity_compare

                real_%  baseline_%
activity_level
Low              57.73       56.84
Moderate         33.46       34.63
High              8.81        8.53

In [ ]:
real_corr = df[numeric_cols].corr()
baseline_corr = baseline[numeric_cols].corr()

corr_delta = baseline_corr - real_corr    #Compare relationships between baseline and real

corr_delta.round(2)

,glucose_mg_dl,heart_rate_bpm,hrv_ms,spo2_percent,sleep_duration_hours,steps
glucose_mg_dl,0.00,0.00,-0.00,-0.02,-0.03,0.00
heart_rate_bpm,0.00,0.00,-0.00,-0.01,0.00,0.01
hrv_ms,-0.00,-0.00,0.00,-0.00,0.00,0.01
spo2_percent,-0.02,-0.01,-0.00,0.00,-0.01,0.00
sleep_duration_hours,-0.03,0.00,0.00,-0.01,0.00,-0.01
steps,0.00,0.01,0.01,0.00,-0.01,0.00